#!/bin/bash
#Looks for every link that points to he same website

# As FieldSeparator for links between
#   "" use ->  '\"'
#   '' use -> "\'"

curl -# $1 | awk '/href/{for(i=1;i<=NF;i++){if(substr($i,0,4) == "href"){print $i}}}' | awk -F '\"' '!/http/{print $2}'
